spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.20.7.37/dc?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，‘wall’用于防火墙
    #打开PSCache，并且指定每个链接PSCache的大小
    pool-prepared-statements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    tomcat:
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 1
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergSql=true;druid.stat.slowSqlMillis=5000
      #最大链接等待超时时间
      max-wait: 60000
      #初始化数量
      initial-size: 1
      #最大活跃数
      max-active: 20
    dbcp2:
      pool-prepared-statements: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.20.7.37
    port: 6379
server:
  context-path: /
