spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.20.8/dc?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.20.8
    port: 6379
server:
  context-path: /
